# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPermission',
            fields=[
            ],
            options={
                'verbose_name': 'global_permission',
                'proxy': True,
            },
            bases=('auth.permission',),
        ),
    ]
