# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-28 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='isEmbeded',
            field=models.BooleanField(default=True),
        ),
    ]
