# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-28 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_isembeded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='isEmbeded',
            new_name='is_embeded',
        ),
    ]
